export var Inicio = [
    {
        id: "0",
        llamada:"Inicio",
        titulo:"Nacimiento",
        informacion:"Esta leyenda comienza con la resolucion de La Fuerza Aerea Francesas con requisitos que provoco la creacion de tres prototipos con ideas múy diferentes.",
        img1:"mirage-2000",
        img2:"",
        img3:"",
        D1:"",
        D2:"",
        D3:"",
        botonA:"Nacimiento",
        botonB: "1",
    },
    {
        id: "1",
        llamada:"Inicio",
        titulo:"Avance",
        informacion:"Luego de la finalizacion del concurso para la seleccion del interceptor ideal, se utiliza el modelo para crear modelos mejorados y versiones con diferentes funciones",
        img1:"5 Dassault_0",
        img2:"",
        img3:"",
        D1:"",
        D2:"",
        D3:"",
        botonA:"Avance",
        botonB:"2",
    },
    {
        id: "2",
        llamada:"Inicio",
        titulo:"Tiempo de Fuego",
        informacion:"Con la bendicion e fuego sobre esta aeronave, se demostro un potencial no descubierto, consiguiendo una gran fama al rededor del mundo entrando en diferentes combates y convirtiendose en una leyenda.",
        img1:"mirage-III",
        img2:"",
        img3:"",
        D1:"",
        D2:"",
        D3:"",
        botonA:"Tiempo de Fuego",
        botonB:"3",
    },
    {
        id: "3",
        llamada:"Inicio",
        titulo:"Jubilacion",
        informacion:"Despues de varios años en actividad cruzo por varias actualizaciones, con historial de vuelo y gran potencial para atacar, provo que llegó a su fin gracias a los avances tecnológico y la aparicion de nuevos aeronaves de combates con más funciones.",
        img1:"mirage-S",
        img2:"",
        img3:"",
        D1:"",
        D2:"",
        D3:"",
        botonA:"Jubilacion",
        botonB:"4",
    },
    {
        id: "4",
        llamada:"Inicio",
        titulo:"Curiosidades",
        informacion:"Además de la historia del aeronave, aquí aparecerá algunos datos extras para los curiosos de la aeronautica.",
        img1:"mirage-CT",
        img2:"",
        img3:"",
        D1:"",
        D2:"",
        D3:"",
        botonA:"Curiosidades",
        botonB:"5",
    },
];
export var Creacion = [
    {
        id: "0",
        llamada:"Creacion",
        titulo:"Nacimiento",
        informacion:"El nacimiento de este avíon comienza con un requerimiento por la Fuerza Aerea Francesa, solicitando un interceptor que sea ligero en peso, con capacidad todo tiempo, que tenga la habilidad de subir 18.000 metros o 59.100 pies en 6 minutos y que sea capaz de superar la velocidad del sonido estando en vuelo nivelado. A esa peticion aparecieron las empresa de Sud-Est, con su avion de ala en flecha y motor mixto, SNCASE SE.212 Durandal, Sud-Ouest, precento su avíon de ala recta y motores puesto en las puntas alaraes SNCASO SO.9000 Trident, por último esta Dassault's con su avíon bimotor y de ala delta MD.550 Mystère Delta.",
        img1:"Inicio/Mystère",
        img2:"Inicio/SNCASE",
        img3:"Inicio/SNCASO",
        D1:"Dassault's MD.550 Mystère Delta",
        D2:"Sud-Est SNCASE SE.212 Durandal",
        D3:"Sud-Ouest SNCASO SO.9000 Trident",
        botonA:"",
        botonB:"",
    },
    {
        id: "1",
        llamada:"Creacion",
        titulo:"Avance",
        informacion:"Despues años de pruebas y eliminando las fallas, a finales de 1954 Dassault realizo un cambio al nombre del modelo pasandose llamar a Mirgae I (significa Espejismo en Frances) lo cual finalizaron de realizar pruebas con el problema de llevar un solo misil aire-aire y de necesitar una gran distancia para despegar. Con los datos obtenidos del último, la empresa decidio crear un nuevo modelo y un poco más grande llamdo Mirage II, con más potencia de motor,  decidieron ir a un objetivo más avaricioso que se implemento en el Mirage III con un 30 porciento más de peso que el primero utilizando unas dimensiones más grande, con la capacidad de tener un vuelo tanto sub-sónico como supersónico y de una manera eficiente, con este último se le incorporó una entrada de aire lateral con un corte de seccion que podia ser graduado automáticamente para una potencia de motor eficiente a casi cualquier velocidad, mientras usaba los motores de nueva generacion llamado SNECMA Atar. En 1957 se dio por finalizado el concurso dando ganador a la empresa Dassault con su Mirage III.",
        img1:"Inicio/Mirage1",
        img2:"",
        img3:"",
        D1:"Dassault's Mirage III Prototipo 001",
        D2:"",
        D3:"",
        botonA:"",
        botonB:"",
    },
    {
        id:"2",
        llamada:"Creacion",
        titulo:"",
        informacion:"",
        img1:"",
        img2:"",
        img3:"",
        D1:"",
        D2:"",
        D3:"",
        botonA:"Volver al Inicio",
        botonB:"6",
    },
];
export var Avance = [
    {
        id: "0",
        llamada:"Avance",
        titulo:"Lo que siguío",
        informacion:"Gracias a la victotia del concurso, la Fuerza Aerea Fracnesa, se solicito una construccion de dies Mirage IIIA de Pre-Produccion. Este último tenía una longitud de dos metros extra en comparacion del portotipo del Mirage III y junto a este cambio, se le icorporo un radar de intercepcion 'Cyrano 1 bis', tambíen se agrego una avíonica estandar de operaciones para la fuera aerea Francesa, se le remplazo el motor SNECMA Atar por uno más poderoso de la mísma empresa que era el modelo Atar 09B, otorgando una potencia de 58.9 Newton (kN) o 13.200 Libras Fuerza (lbf), se le dío la capacidad de incorporar un cohete inpulsor SEPR 841 que al activarse le permitia ganar 35.000 pies de altura o 10.670 metros de altura en solo un minuto y medio, otro cambio de la lista fue la incorporacion de un paracídas para reducir la distancia de fernada en el aterrizaje. Los últimos seis modelo se le remplazo el motor por uno de produccion Britanica Rolls-Royce Avon 67 con potencia de empuje de 71.1 KN o 16.000 lbs. Durante los vuelos de prueba a inicio de 1958 hasta inicio de 1961 demostrando la capacidad de vuelo demostrando ser el primer avíon de Europa en llegar a la velocidad de mach 2.2 en vuelo nivelado. A pesar que tuvo mucho exito el uso de los motores Britanicos, se decidio no incorporarlo en la produccion en seria de la serie. ",
        img1:"avance/M30",
        img2:"avance/M30A",
        img3:"avance/misiles2",
        D1:"Mirage III A 001",
        D2:"Piloto de prueba Roland Galvany al lado del Mirage III 001",
        D3:"Misiles franceses Matra R530 que usará los siguientes modelos del mirage III",
        botonA:"",
        botonB:"",
    },
    {
        id: "1",
        llamada:"Avance",
        titulo:"Inicio de la produccion",
        informacion:"El primer avíon de produccion en serie de la familia comenzo con el Mirage III C, que comparado al modelo A, era medio metro más largo para llevar dos cañones fijos DEFA con capacidad de llevar municio de 30 milimetros de ancho por 113 milimetros de largo, a la vez, se le incorporó 5 pilones de carga, con capacidad de llevar 2 tanques de combustibles desechables, misiles de guía infraroja AIM-9 Sidwinder modelo B y que despues serian remplazado por un modelo de produccion Francesa, tambíen de guía infraroja, llamado Matra R550 Magic y por último se le dio la capacidad de llevar un misiles un poco más grande llamado Matra R530, este último tenia la capacidad de ser guiado por radar o por infrarojo. Mientras se prodicia los 95 avíones del modelo explicado, la Fuerza Aerea Francesas solicito la produccion de 63 modelo biplaza para el entrenamiento, con diferencia del modelo C, se le extrajo los cañones de DEFA  y al mismo tiempo se lo alargo cerca de un metro para ubicar el segundo pilóto.",
        img1:"avance/M31A",
        img2:"avance/M31",
        img3:"avance/M33",
        D1:"Mirage III modelo C",
        D2:"Version de entrenamiento Mirage III modelo B",
        D3:"Mirage III C con dos misiles R550 y los R530",
        botonA:"",
        botonB:"",
    },
    {
        id:"2",
        llamada:"Avance",
        titulo:"Primera Modernizacion",
        informacion:"Mientras se producia el Mirage IIIC, la empresa desarrollaba el modelo E que tenia algunas diferencias y mejoras, una de ellas fue el alarge de 30 centimetro en el frente del avíon para poder agregar el nuevo radar de funcionamiento Aire/Tierra Thompson CDF Cyrano II que tambíen incluia un Receptor de Alerta de Radar (del acrónimo RWR que proviene del ingles Radar Warning Receiver), se le incorporó un avionica mejorada, mayor capacidad de combustible, por último se agrego un sistema de navegacion Doppler de la empresa Inglesa Marconi ubicado debajo de la cabina, tambíen se remplazo el motor por un motor más nuevo Atar 09C que más adelante se le agrego una salida de escape variable para un empuje más eficiente, este modelo se le agrago la capacidad de realizar ataque a tierra. Desde su primer vuelo en 1964 hasta 1971 se transformo en el avíon más exportado de la familia. Gracias al modelo creado se creo dos variantes, una de ellas era variante de reconocimiento llamado Mirage III R, que remplazaba el radar de la nariz por un conjunto de 5 cámaras fotograficas con capacidad de conseguir imagenes paronámicas y se lo equipo con avíonica similar al Mirage III C, el segundo modelo creado fue conocido como Mirage IIID que era un modleo biplaza para el entrenamiento.",
        img1:"avance/M31R",
        img2:"avance/M32",
        img3:"avance/M51",
        D1:"Frente del avion con cámaras de observacion para vuelos de reconocimiento",
        D2:"Mirage III D, para entrenamiento",
        D3:"Mirage III E con misiles aire-aire",
        botonA:"",
        botonB:"",
    },  
    {
        id:"3",
        llamada:"Avance",
        titulo:"",
        informacion:"A pesar que los únicos usuarios del Mirage III C fueron israel y Sudáfrica, gracais a la victoria de Israel usando ese modelo en las guerras contra sus vecinos, creo una reputacion muy positiva que tambíen se le otorgó puntos extra al detalle de su bajo costo en operatividad y simplesa para reparar, generó una gran demanda en diferentes paises y se le ponia cierta denominacion dependiendo del pais donde se realizaria la exportacion y con algunas modificaciones en la avionica. Como ejemplo, se usaba la denominacion 'J' para la exportacion a Israel, la denomincanion 'E' para España, la 'V' para venezuela, la denominaciones con letra 'A' era para la exportacion para Argentina, entre otros más. Despues e ver su potencial en la guerra de israel, el Mirage obtuo una notoriedad en el mundo y con esto, la empresa, se aprobecho para crear diferentes modelos especializado en diferentes funciones, como un modelo que era un bombarero nuclear, hasta otro que tenia la capacidad de realizar despegue vertical.",
        img1:"Jubilacion/I1",
        img2:"avance/M34E",
        img3:"avance/M34A",
        D1:"Mirage III C de la Fuerza Aerea Israel",
        D2:"Mirage III E de la Fuerza Aerea Española",
        D3:"Mirage III E de la Fuerza Aerea Argentina",
        botonA:"",
        botonB:"",
    },  
    {
        id:"4",
        llamada:"Avance",
        titulo:"Projectos de Técnologias",
        informacion:" Con la teoria militar sobre la destruccion de los aeropuertos princiaples ante una guerra total contra la Uníon Sovietica, se crea una popularidad de los aviones de Despegue y Aerrizaje Vertical, tambíen conocido como VTOL (del ingles Vertical Takeoff and Landing), que su funcion principal era en hacer despegues y ateruzajes en pistas cortas o de manera vertical sin depender de aeropuertos, y a peticion de la Fuerza Aerea Francesas, se crea el primero de los dos modelos VTOL de Dassault llamado Balzac V, usando el modelo del prototipo del Mirage III A se le modifica para que pueda portar Ocho motores Rolls.Royce RB.108 junto a una modificacion del chasis para el ingreso de aire a esos motores y salidas de escapes del mismo, teniendo su primer vuelo el 12 de octubre de 1962 y obteniendo su primera prueva de vuelo estacionario libre el 18 de octubre del mismo año. El 10 de enero de 1964 tuvo un accidente mientras hacia unas de las pruebas de vuelo vertical a baja altura, causando un vuelco por inestabilidad en los motores y esto generó la muerte del pilóto. Gracias a los datos obtenido del Balzac V y con el requerimiento de la OTAN (acronimo de Organizacion del Tratado del Atlántico Norte) sobre tener un avíon con capacidad de realizar despegue y aterrizaje vertical, se considero trabajar en un projecto más ambicioso llamado Mirage IIIV, en la que usaba motore más potentes que le permitía ir a velocidades de mach 1.32 (1630km/h), desafortunadamente el 28 de nobiembre de 1966 durante una prueba de estabilidad con los motores verticales se generó una perdida de potencia, lo que entro en perdida y el pilóto se vio obligado a ejectarse pero el paracaidas no se abrio por completo generando la segunda muerte del projecto. Desafortunadamente Dassault dio por cerrado el projecto por perder el concurso contra Hawker Siddeley P1127 (que a la produccion en serie sería llamado Hawker Siddeley Harrier).",
        img1:"avance/VTOL36",
        img2:"avance/VTOL35",
        img3:"",
        D1:"Dassault Balzac V",
        D2:"Dassault Mirage IIIV",
        D3:"",
        botonA:"",
        botonB:"",
    },
    {
        id:"5",
        llamada:"Avance",
        titulo:"El hermano Mellizo",
        informacion:"Mientras se desarrollaba el Dassault Mirage III, y para cumplir el requerimiento de Franca sobre un avíon bombardero con capacidad de lanzar una bomba nuclear, se probo una idea diferente que hacer el mismo avíon pero más grande y con capacidad de realizar bombardeo, se desarrollaba lo que seria el Dassault Mirage IV. Ese avíon, a pesar que era más grande, tenia la capacidad de realizar vuelos con velocudad que alcanza al mach 1.85 o 2.285 km/h gracias a sus motores gemelos SNECMAA Atar que le permitia llevar una carga de 7.200 kilogamos en carga en 3 grandes pilones de sujecion, usualmente se usaban los pilones debajo del ala para grandes tanques de combustibles externo y se dejaba el pilon interno para transportar bombas, pero su mision principal es portar una bomba nuclear de caida libre. A causa de la aparicion de misiles anti-aereos precisos por parte de la Uníon sovietica, Francia decidio reducir la altura de vuelo de 13.000 metros de altura a vuelo cerca del suelo, con el nuebvo cambio de nivel de vuelo reducia la posibilidad de ser detectado por los radares pero redujo el radio de vuelo del mismo y para eso Francia, como complemento del bombardero, decidio comprar unidades de aviones cisternas Boeing KC-135 Stratotanker para repostar en el aire a los Mirage, lo cual permitío extender el rango de vuelo. La bomba nuclear de caida libre que cargaba el avíon eran los modelos AN-11 o el AN-22 pero con el cambio de altura de vuelo, además del avance de las capacidades anti-aerea de la Unio Sovietica, resulto defectuoso el uso de esas bombas, para eso se creo un nuevo sistema de arma nuclear del modelo ASMP (del frances Air-Sol Moyenne Portée) con rango de vuelo cercano a los 400 kilometros y una carga nuclear entre 150 a 300 kilotones. Para reducir la distancia de despegue, habilito la instalcion del sistema JATO (Jet Assisted Take-Off) y un sistema de paracídas para reducir la distancia de frenada. En la década de 1980 solamente 18 modelos consiguieron la modificacion para llevar los misiles nucleares, fureon llamado como Mirage IV P, tambíen llebaba un pod de cámaras fotograficas para realizar reconocimiento. En 1996 se le saco el rol de llevar misiles nucleares para agregarlo a los nuevos y más modernos Dasault Mirage 2000, en 2020 fue remplazado por el Dassault Rafael que tiene la capacidad de realizar las misma funciones de manera más eficiente. Una curiosidad que tenia el bombardero, es que no usaba un radar en el frente de la nariz, sino, un radar en la parte ventral del mismo.",
        img1:"avance/M3M4",
        img2:"avance/M41",
        img3:"avance/M42",
        D1:"Mirage III C junto al primer modelo del Mirage IV",
        D2:"Mirage IV mostrando el radar en la panza",
        D3:"Mirage IV con asistencia de despegue llamdo JATO",
        botonA:"",
        botonB:"",
    },
    {
        id:"6",
        llamada:"Avance",
        titulo:"Actualizacion simplificada",
        informacion:"Despues de la victoria de Isarel y gracias la informacion obtenia de la actuacion de los Mirage III C, el país solicito un un modelo mejorado y obtimizado para el ataque a tierra, a esto se realizo un modelo de casi la misma dimension con pequeñas diferencia y preparado para el ataque a tierra. Para esto se le modificacion la nariz a una dimension que se mejore la vista hacia el piso pero sin perder la aerodinamica, lo malo de lo último es la eliminacion del uso de los misiles guiado por radar, pero se le permitio el uso de los misiles de guía infrarojo para la autodefensa. Otra diferencia fue la aligeracion del peso lo que le permitío tener un poco más de autonomía y aparte, se le agrego dos puntos de cargas extra para la carga de bombas. Desafortunadamente y para evitar el aumento de las tenciones en el Medio Oriente Charles de Gaulle creo un envargo de armamento a Isarael, lo que Dassault tuvo que ingeniarsela para evadir ese embargo de armas para la entrega a Israel, al final el país reciviría los modelos pedidos pero desarmado y enpaquetados para arme en ese país. Luego de la cancelacion de las compras, Isarel y Dassault ingeniaron una manera de entregar los planos del mismo para la produccion local pero llamandose IAI Nesher. A pesar de todo el drama, el Mirage 5 fue famoso, lo que provoco una exportacion hacia Colombia, Peru, Chile, Paquistan, Sur-Africa y algunos paises del medio oriente. Durante la decada de 1970 se le modifico mejorando la avíonica, poniendo un radar mejorado y agregando un motor SNECMA Atar 9K con una potecia de 49.2kn de empuje y con posquemador daba 70.6kn de empuje, en algunos paises y por último se le incorporó un estabilizador fijo llamado canards. A este modelo de Mirage lo llamaro Mirage 50,  este últimofue vendido a Chile, que despues drain un actualizacion para chear el Atlas Cheetah, y a Israel, que haria una produccion bajo licencia llamado IAI Kfir.",
        img1:"avance/M53",
        img2:"avance/M52",
        img3:"avance/M55",
        D1:"Mirage V susando la carga máxima de bombas",
        D2:"Mirage V de la Fuerza Aerea Chilena",
        D3:"Mirgae V en su version Atlas Cheetah",
        botonA:"",
        botonB:"",
    },
    {
        id:"7",
        llamada:"Avance",
        titulo:"El más nuevo",
        informacion:"A causa de experimentos fallidos, decidieron desarrollar un mirage III modernizado llamado Mirage 2000, en 1975 Francia aacepta el desarrollo del mismo usando la mismas funciones del Mirage III pero con avance e tecnologia e inovaciones y con una capacidad secundario de realizar ataque a tierra. Entre las mejoras incuia un rediseño en el fuselaje, un motor más potente, una zonda de combustible para el repostaje aerea, sistema Fly by Wire (un sistema de manejo que eliminaba las poleas e hidraulicos) para un vuelo más controloado, radar mejorado y el cono de admision tiene un sistema de graduacion automática, lo que probocaba una gran eficiaencia de vuelo a cualquier altura y velocidad. Solamente hiceron un un modelo del mismo, llamado Mirage 2000 N, que se le dío la capacidad de realizar aataques nucleares. Para hacerle competenciaa al F16 que estaba entrando con fuerza en el mercado y cerca del sigloe XXI, el Mirage 2000 C recibiero una modernizacion para realizar funciones tanto de superioridad aerea como apollo aereo en un único vuelo, con radares y avíonicas mejoradas lo llamaron Mirage 2000-5 y en 2005 crearon un nuevo paquete de modernizacion con mejor electronica de vuelo, los que recibian esta mejora serian llamado como Mirage 2000-5F.",
        img1:"avance/M20",
        img2:"avance/M21",
        img3:"avance/M22",
        D1:"Mirage 2000 5F de la Fuera Aerea Fancés",
        D2:"Mirage 2000 5F mostrando las bombas guiadas",
        D3:"Version de ataque a tierra Mirage 2000N",
        botonA:"",
        botonB:"",
    },
    {
        id:"8",
        llamada:"Avance",
        titulo:"",
        informacion:"",
        img1:"",
        img2:"",
        img3:"",
        D1:"",
        D2:"",
        D3:"",
        botonA:"Volver al Inicio",
        botonB:"6",
    },
];
export var Combate = [
    {
        id:"0",
        llamada:"Combate",
        titulo:"La bendicion de fuego",
        informacion:"A causa de los malestares políticos y sociales que tenia Isarael con sus vecinos, el país decidio modernizar y potenciar su flota aerea deciden comprar un lote de  Mirage III CJ con una pequeña modificacion en la avionica para un vuelo más adaptado al entrenamiento de los Pilótos Israelitas, ante todo esto, solicitaron un total de 77 Mirage III entre el modelo biplaza de entrenamiento B, el monoplaza CJ y recivieron equipos para modificar 2 modelos que altera la nariz para el reconocimiento, similar al modelo R, a este último lo llamaron Mirage III CJ (R). En junio de 1967, el país lo útilizo en durante la tercera Arabe-Isaelí, tambíen llamado como la Guerra de Los Seis Días, donde crea la Operacion Focus para aprobechar los aviones disponibles y en eso usa los Mirage III CJ para tacticas de superioridad aerea, teniendo cuidado al peor enemigo tuvo la Fuera Aerea Israelita que eran las defensa anti-aerea como los tipos SAM (Surface to Air Missile, que en español es Misile de Tierra Aire). Existieron casos de combate aereo de los Pilotos israelitas en Mirage contra algunos pilotos Jordanos en Hawker Hunter, hubo casos de combates contra pilotos Egipcios en Sukoy 7, tamíen existieron combate contra MiKoyan-Gurevich 19 y tambíen hubo combate contra los homologos Mikoyan-Gurevich 21 F13 incluido del modelo PF. Las perdidas reconocidas durante esa guerra fue un total de 250 aviones Israelitas contra 600 aviones perdido por parte de la Coalicion Arabe, veinticuatro pilotos de ambos bandos perdieron la vida durante esa guerra. Durante el 6 de octubre al 25 de ocubre de 1973 ocurrió la cuarta guerra Arabe-Israelita, tambíen conocida como la Guerra de Octubre o la Guerra de Yom Kippur donde la actuacion de la fuerza aerea tuvo más combate aereos que en la guerra anterior, en este suceso los Mirage III CJ estuvieron realizando misiones de patrullas y algunas veces realizar misiones de escota de los A-4 Skyhawk y a veces de los F-4 Phantom II. Existeron combates aereos entre los Mirage III CJ contra los pilótos Egipcios, pero los Misiles de tipo SAM seguian siendo el pero enemigo de los aviones Israelistas. En este suceso Israel perdío 102 aviones lo cual 11 de ellas eran de los mirage III CJ. A pesa que las perdidas, gracias a este suceso el Mirage III gano una gran reputacion a nuvel mundial.",
        img1:"Combate/I2",
        img2:"Combate/I1",
        img3:"Combate/I4",
        D1:"Camara de combate de un mirage Israelita al momento de derribar un Mig 21 Egipcio",
        D2:"Imagen de unas de las pocas bajas del mirage III a causa de un Mig 21 ocurrido en la guerra de Yom Kippur",
        D3:"Imagen sacada en un Mirage IIIR pasando un aerodromo egipcio despues de una operacion de ataque para analizar los daños",
        botonA:"",
        botonB:"",
    },
    {
        id:"1",
        llamada:"Combate",
        titulo:"Tercera actuacion en Guerra",
        informacion:"Sur-Africa compro 16 modelos interceptor Mirage III CZ, 17 multi-funcion Mirage III EZ y 4 modelos de reconocimiento Mirage III RZ unicamente lo usaban para misiones de reconocimiento por cuasas de la avionica y los radares que no funcionaban como lo esperaban para las misiones de combates aereos o de ataque a tierra, a causa de esto estuvieron obligado a comprar los Mirage F1 para considerar obsoletos a los Mirage III. Durante este combate solamente usaron mucho los Mirage III RZ utilizando tacticas de fotografia mientras realizaba una maniobra similar al Giro de Immelmann y con eso conseguir una imagen fotografia para el reconocimiento. No extio situaciones de combate aereo con los Mirage III.",
        img1:"Combate/SA1",
        img2:"mirage-III",
        img3:"",
        D1:"Mirage III CZ en vuelo de formacion",
        D2:"Mirage III usando el pod de choetes",
        D3:"",
        botonA:"",
        botonB:"",
    },
    {
        id:"2",
        llamada:"Combate",
        titulo:"Guerra Indo-Paquistaní",
        informacion:"Indía, Paqustan del Este y Paquistan del Oeste, antes bajo el mando del Raj Britanico, obtubieron la indenpendencia del mismo y de reino Unido despues de 1947, pero como la poblacion tenia una cantidad de cercana al 25% de Mulsumanes decidieron ubicarlos en dos territorios a 1.600 kilómetreos de distancia teniendo a Indía entre medio, pero aún quedaron Budista en los territorios de Paquistan lo se creo un grupo rebelde armado apoyado por Indía para reducir el poder político de Paquistan, cuando descubrieron la existencia y de donde venian la ayuda, el pais tomo la iniciativa de eliminar a esas fuerzas rebeldes y crear una venganza contra Indía llamado Operacion Chengiz khan, en esto se aprobechaba realizar la iniciativa de destruir los aerodromos de Indía como hizo Egipto contra Israel en la Cuanta Guerra Arabe-Israelí, para eso usaron un grupo de Mirage III DP, junto a F-86 sabre e British Camberra, desafortunadamente para Paquistan los daños terminaron siendo minimos e Indía no tubo problema en usar los aerodromos para obtener la supremacia aerea.",
        img1:"Combate/P1",
        img2:"Combate/P2",
        img3:"",
        D1:"Mirage III E",
        D2:"Vuelo en formacion junto a Shenyang F-6 y un Lockheed F-104",
        D3:"",
        botonA:"",
        botonB:"",
    },
    {
        id:"3",
        llamada:"Combate",
        titulo:"Ultima Guerra y con sorpresa",
        informacion:"En 1982, durante la tercera y última dictadura militar, el estado Argentino dirigio una operacion para reconquistar las Islas Malvinas del dominio Ingles, despues de exitosa invacion sorpresiva, Inglaterra envío una flota militar para recuperarlos y para eso Argentina envíaba aviones Douglas A4 Skyhawk modelos B, C y Q, junto a un par de misiones hecho con los IAI Dagger (Mirage V producido en Israel), Mirage III EA y los Dassault Etendart para las misiones anti-buque utilizando bombas para atacar a tiera con la espoleta calibrada para que explote al segundo despues del impacto y con eso evitar daños al avion por la explosion, con ecepcion de los etendart que tenian la posibilidad de llevar los misiles anti-navios Exoet, para concretar ese bombardeo y empenzando a los 50 kilómetros del objetivo, era necesario realizar un vuelo por debajo de los 15 metros de altura en la mayor velocidad posible o que el aparato pueda llegar, además, era necesario economizar el consumo de combustible a causa que estaban en el límite de autonomía de los aparatos, a pesar que tenian instalados los tanques de combustibles externos, y con eso podiar realizar ataques sorpresas por volar por debajo de la deteccion del radar ingles, solamente existio un caso de combate aereo entre los Mirage III EA y la version maritima del Hawker Siddeley Harrier llamado Sea Harrier, desafortunadamente se perdío ese combate lamentando una baja de los Mirage III EA. Otro infortunio sucedido en este conflicto fue una perdida de un avíon por fuego aliado. Al finalizar la guerra, Argentina perdío 73 aviones e Inglaterra perdío 10 aviones.   ",
        img1:"Combate/A1",
        img2:"Combate/A2",
        img3:"",
        D1:"Mirage III E de la Fuerza Aérea Argentian",
        D2:"Mirage III E tomado esde un barco Británico durante una ofensiva aerea por parte de Argentina",
        D3:"",
        botonA:"",
        botonB:"",
    },
    {
        id:"4",
        llamada:"Combate",
        titulo:"",
        informacion:"",
        img1:"",
        img2:"",
        img3:"",
        D1:"",
        D2:"",
        D3:"",
        botonA:"Volver al Inicio",
        botonB:"6",
    },
];
export var Jubilacion = [
    {
        id:"0",
        llamada:"Jubilacion",
        titulo:"Jubilacion",
        informacion:"Ante el desgaste del aparato más el avance de nuevas tecnologia de diferente tipos, los Mirage III estuvieron en diferentes paises con un uso de 40 a 60 años en servicio, con un todal cercado a los 700 aviones exportado de todos los modelos producido desde su inicio hasta 1970, siendo que, Israel fue el primero en retirar sus modelos vendiendolo a Argentina entre 1978 a 1982, Belgica Retiró sus Mirage III en 1989, Australia retiró sus 116 avíones en 1987 pero vendiendo 50 aparatos a Paqustán, Francai retiró sus aviones en 1994 y siendo remplazado por los Mirage 2000, España vendío sus aparatos en 1992 a Paqustan, Libano retiró sus aparatos vendiendo a Paqustan en el 2000, Sur-Africa retiró sus Mirages modernizado al estandar Altlas Cheeta en 2003 siendo remplazado por el Saab 39 Gripen, Suiza retiró sus aviones en 2003 pero vendío un Mirage IIID Biplaza para para el uso civil, Brazil retiró sus modelos en 2005, Venezuela Retiró sus aviones mejorado en 2009, donando seis Mirage a Ecuador, Argentina retiró los Mirage en 2015 sin tener un avion para rempazarlo y Paquistan Esta actualizando los mirage usando el proejcto ROSE estipulando que en 2025 serán remplazado por los JF-17",
        img1:"",
        img2:"",
        img3:"",
        D1:"",
        D2:"",
        D3:"",
        botonA:"",
        botonB:"",
    },
    {
        id:"1",
        llamada:"Jubilacion",
        titulo:"",
        informacion:"En argentina descansan 3 modelos de Mirage III en el museo Nacional de Aeronáutica de Argentina, en Buenos Aires. Otro Mirage III descansa en el Museo Interfuerzas de Estancia San Romana en San Luis, y el último descansa en el Liceo Milirar Aeronautico, en la provincia de Santa Fe.",
        img1:"Jubilacion/A1",
        img2:"Jubilacion/A2",
        img3:"",
        D1:"",
        D2:"",
        D3:"",
        botonA:"",
        botonB:"",
    },
    {
        id:"2",
        llamada:"Jubilacion",
        titulo:"",
        informacion:"En Isarael recupero algunos modelos venvido en Argentina para ponerlo en expocicion militar en el Museo Israelí de la Fuerza Aerea.",
        img1:"Jubilacion/I1",
        img2:"Jubilacion/I2",
        img3:"",
        D1:"",
        D2:"",
        D3:"",
        botonA:"",
        botonB:"",
    },
    {
        id:"3",
        llamada:"Jubilacion",
        titulo:"",
        informacion:"Australia dejo cerca de 16 aparatos repartido en museo al rededor de su pais, con exepcion de  uno que fue entregado a la Historical Aircrafth Restoration Society (HARS),donde se encargan de precervar los aviones que reciven para que esten funcionales para las expociciones.",
        img1:"Jubilacion/AU1",
        img2:"Jubilacion/AU2",
        img3:"Jubilacion/AU3",
        D1:"",
        D2:"",
        D3:"",
        botonA:"",
        botonB:"",
    },
    {
        id:"4",
        llamada:"Jubilacion",
        titulo:"",
        informacion:"Brazil dejo su único suverviviente en el Parque de Material Aeronautico de São Paulo",
        img1:"Jubilacion/B1",
        img2:"",
        img3:"",
        D1:"",
        D2:"",
        D3:"",
        botonA:"",
        botonB:"",
    },
    {
        id:"5",
        llamada:"Jubilacion",
        titulo:"",
        informacion:"Sur-Africa dejo algunos aviones en el Museo de la Fuerza Aerea de Sur-Africa",
        img1:"Jubilacion/SA1",
        img2:"Jubilacion/SA2",
        img3:"",
        D1:"",
        D2:"",
        D3:"",
        botonA:"",
        botonB:"",
    },
    {
        id:"6",
        llamada:"Jubilacion",
        titulo:"",
        informacion:"Francia dejo varios de los Mirage III en sectore abiertos y en los museo aeronauticos del pais",
        img1:"Jubilacion/F1",
        img2:"Jubilacion/F2",
        img3:"Jubilacion/F3",
        D1:"",
        D2:"",
        D3:"",
        botonA:"",
        botonB:"",
    },
    {
        id:"7",
        llamada:"Jubilacion",
        titulo:"",
        informacion:"Suiza dejo dos modelos de Mirage III en el Museo de Flieger Flab, pero un modelo retirado fue vendido para uso civil en expocisiones aereas apodado Black Widow.",
        img1:"Jubilacion/S1",
        img2:"Jubilacion/S2",
        img3:"",
        D1:"",
        D2:"",
        D3:"",
        botonA:"",
        botonB:"",
    },
    {
        id:"8",
        llamada:"Jubilacion",
        titulo:"",
        informacion:"Mirage III de Paquistan en servicio hasta la adquicicion de los aviones JF-17.",
        img1:"Jubilacion/P1",
        img2:"Jubilacion/P2",
        img3:"Jubilacion/P3",
        D1:"",
        D2:"",
        D3:"",
        botonA:"",
        botonB:"",
    },
    {
        id:"9",
        llamada:"Jubilacion",
        titulo:"",
        informacion:"",
        img1:"",
        img2:"",
        img3:"",
        D1:"",
        D2:"",
        D3:"",
        botonA:"Volver al Inicio",
        botonB:"6",
    },
];
export var Curiosidades =[    
    {
        id:"0",
        llamada:"Curiosidades",
        titulo:"Mecánicas",
        informacion:"Dicho en la primera seccion del al página, una de las ideas que mejoró la potencia del motor fue la incoporacion cono de difusion variables, esto permite adaptarse a la velocidad del avion para que halla una entrada de aire optima para el funcionamiento del motor, cuando se llega a velocidad supersónica, se crea una onda de choque que actua como freno para el aire que entra al motor, lo que genera una reduccion en la velocidad del aire y enita que se provoque turbulencia dentro del motor.",
        img1:"Curiosidades/1Subsonico_1",
        img2:"Curiosidades/2Supesonico",
        img3:"https://www.youtube.com/embed/iO-O64q7d_o",
        D1:"Entrada de aire a velocidad subsonica, con el difusor dentro de la entrada de aire",
        D2:"Entrada de aire a velocidad Supersónica, con difusor adelantado, la onda de choque actua de freno para la entrada de aire actuando como freno para el aire que va a entrar al motor",
        D3:"Entrada de aire a velocidad variable en un cono fijo bajo el Efecto Schlieren",
        botonA:"",
        botonB:"",
    },
    {
        id:"1",
        llamada:"Curiosidades",
        titulo:"",
        informacion:"",
        img1:"Curiosidades/4difusorMarcado",
        img2:"",
        img3:"",
        D1:"Zona marcada del difusor del Mirage III, en verde es la zona exterior de la entrada de aire, en amarillo es el difusor, y en rojo es un corte que donde se aleja la entrada de aire al chasis del avíon para una entrada limpia sin turbulencia.",
        D2:"",
        D3:"",
        botonA:"",
        botonB:"",
    },
    {
        id:"2",
        llamada:"Curiosidades",
        titulo:"",
        informacion:"",
        img1:"",
        img2:"",
        img3:"",
        D1:"",
        D2:"",
        D3:"",
        botonA:"Volver al Inicio",
        botonB:"6",
    },
]